# -*- coding: utf-8 -*-
"""kenya_inflation_analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tq5l3Li1j_emxkArayBF7jfnbMvFZNZI
"""

#Kenya Inflation Analysis (2016-2025)
#Author: Benedita Kamau
#Data Source: Kenya National Bureau of Statistics (KNBS)


import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.linear_model import LinearRegression
import numpy as np

# Load the dataset (your updated file)
df = pd.read_excel("/content/Inflation(2016-2025).xlsx")

#Preview the data
print(df.head())
print(df.shape)
print(df.dtypes)
print(df.isnull().sum())

#Cleaning the data
#Extract just the Year from the date column, without changing the original column
df['Year'] = pd.to_datetime(df['National Average Retail Prices of Selected Commodities per year']).dt.year
#Check missing values per column
print("Missing values per column:")
print(df.isnull().sum())
#Sort by Year
df = df.sort_values('Year').reset_index(drop=True)

print("\nData with Year column added:")
print(df[['National Average Retail Prices of Selected Commodities per year',
          'Year', 'Overall CPI', 'Overall Rate of Inflation']])

#Visualisations
sns.set_theme(style="whitegrid")
plt.rcParams['figure.figsize'] = (12, 5)

#CHART 1: Overall Inflation Rate (2016–2025)
plt.figure()
plt.plot(df['Year'], df['Overall Rate of Inflation'],
         color='steelblue', linewidth=2, marker='o', markersize=6)
plt.axhline(y=5, color='red', linestyle='--', linewidth=1, label='5% threshold')
plt.title('Kenya Overall Inflation Rate (2016–2025)', fontsize=14, fontweight='bold')
plt.xlabel('Year')
plt.ylabel('Inflation Rate (%)')
plt.xticks(df['Year'])
plt.legend()
plt.tight_layout()
plt.savefig('chart1_overall_inflation.png', dpi=150)
plt.show()
print("Chart 1")

#CHART 2: Overall CPI Trend (2016–2025)
plt.figure()
plt.plot(df['Year'], df['Overall CPI'],
         color='seagreen', linewidth=2, marker='o', markersize=6)
plt.title('Kenya Overall CPI Trend (2016–2025)', fontsize=14, fontweight='bold')
plt.xlabel('Year')
plt.ylabel('Consumer Price Index')
plt.xticks(df['Year'])
plt.tight_layout()
plt.savefig('chart2_overall_cpi.png', dpi=150)
plt.show()
print("Chart 2")

#CHART 3: Petrol vs Diesel Prices (2016–2025)
plt.figure()
plt.plot(df['Year'], df['Petrol/1 litre'], color='darkorange',
         linewidth=2, marker='o', label='Petrol')
plt.plot(df['Year'], df['Diesel/1 litre'], color='steelblue',
         linewidth=2, marker='o', label='Diesel')
plt.title('Petrol vs Diesel Prices in Kenya (2016–2025)', fontsize=14, fontweight='bold')
plt.xlabel('Year')
plt.ylabel('Price (KES per litre)')
plt.xticks(df['Year'])
plt.legend()
plt.tight_layout()
plt.savefig('chart3_petrol_vs_diesel.png', dpi=150)
plt.show()
print("Chart 3")

#CHART 4: Diesel Prices vs Year (2016–2025)
plt.figure()
plt.plot(df['Year'], df['Diesel/1 litre'], color='steelblue',
         linewidth=2, marker='o', markersize=6)
plt.title('Diesel Prices in Kenya (2016–2025)', fontsize=14, fontweight='bold')
plt.xlabel('Year')
plt.ylabel('Price (KES per litre)')
plt.xticks(df['Year'])
plt.tight_layout()
plt.savefig('chart4_diesel_prices.png', dpi=150)
plt.show()
print("Chart 4")

#CHART 5: Petrol Prices vs Year (2016–2025)
plt.figure()
plt.plot(df['Year'], df['Petrol/1 litre'], color='darkorange',
         linewidth=2, marker='o', markersize=6)
plt.title('Petrol Prices in Kenya (2016–2025)', fontsize=14, fontweight='bold')
plt.xlabel('Year')
plt.ylabel('Price (KES per litre)')
plt.xticks(df['Year'])
plt.tight_layout()
plt.savefig('chart5_petrol_prices.png', dpi=150)
plt.show()
print("Chart 5")

#CHART 6: Staple Food Prices vs Year (2016–2025)
plt.figure()
foods = ['Sugar/2 kg', 'Onions/1 kg', 'Tomatoes/1 kg', 'Kale-Sukuma Wiki/1 kg']
colors = ['tomato', 'seagreen', 'steelblue', 'orange']
for food, color in zip(foods, colors):
    plt.plot(df['Year'], df[food], color=color, linewidth=1.5,
             marker='o', label=food.split('/')[0])
plt.title('Staple Food Prices in Kenya (2016–2025)', fontsize=14, fontweight='bold')
plt.xlabel('Year')
plt.ylabel('Price (KES)')
plt.xticks(df['Year'])
plt.legend()
plt.tight_layout()
plt.savefig('chart6_staple_foods.png', dpi=150)
plt.show()
print("Chart 6")

#Insights and prediction model
#Key insights
print("=" * 50)
print("KEY INSIGHTS")
print("=" * 50)

#Highest and lowest inflation years
max_inflation_row = df.loc[df['Overall Rate of Inflation'].idxmax()]
min_inflation_row = df.loc[df['Overall Rate of Inflation'].idxmin()]

print(f"\nHighest inflation: {max_inflation_row['Overall Rate of Inflation']}%"
      f" in {int(max_inflation_row['Year'])}")
print(f"Lowest inflation: {min_inflation_row['Overall Rate of Inflation']}%"
      f" in {int(min_inflation_row['Year'])}")

#Average inflation over the period
avg_inflation = df['Overall Rate of Inflation'].mean()
print(f"Average inflation (2016–2025): {avg_inflation:.2f}%")

#Fuel price growth
petrol_growth = ((df['Petrol/1 litre'].iloc[-1] - df['Petrol/1 litre'].iloc[0])
                 / df['Petrol/1 litre'].iloc[0]) * 100
diesel_growth = ((df['Diesel/1 litre'].iloc[-1] - df['Diesel/1 litre'].iloc[0])
                 / df['Diesel/1 litre'].iloc[0]) * 100
print(f"\nPetrol price growth (2016–2025): {petrol_growth:.1f}%")
print(f"Diesel price growth (2016–2025): {diesel_growth:.1f}%")

#Sugar price growth
sugar_growth = ((df['Sugar/2 kg'].iloc[-1] - df['Sugar/2 kg'].iloc[0])
                / df['Sugar/2 kg'].iloc[0]) * 100
print(f"Sugar price growth (2016–2025): {sugar_growth:.1f}%")

#Prediction model (Linear Regression)
print("\n" + "=" * 50)
print("INFLATION FORECAST MODEL")
print("=" * 50)

#Prepare data for the model
X = df[['Year']]
y = df['Overall Rate of Inflation']

#Train the model
model = LinearRegression()
model.fit(X, y)

#Predict inflation for the next 3 years
future_years = pd.DataFrame({'Year': [2026, 2027, 2028]})
predictions = model.predict(future_years)

print("\nPredicted Inflation Rates:")
for year, pred in zip(future_years['Year'], predictions):
    print(f"{year}: {pred:.2f}%")

#CHART 7: Actual vs Predicted Inflation
plt.figure()
plt.plot(df['Year'], df['Overall Rate of Inflation'],
         color='steelblue', marker='o', label='Actual Inflation')
plt.plot(future_years['Year'], predictions,
         color='red', marker='o', linestyle='--', label='Predicted Inflation')
plt.title('Kenya Inflation: Actual vs Predicted (2016–2028)',
          fontsize=14, fontweight='bold')
plt.xlabel('Year')
plt.ylabel('Inflation Rate (%)')
plt.legend()
plt.tight_layout()
plt.savefig('chart7_inflation_forecast.png', dpi=150)
plt.show()
print("Chart 7")

#Model performance
r_squared = model.score(X, y)
print(f"\nModel R² score: {r_squared:.3f}")
print("(R² closer to 1 = stronger linear relationship; closer to 0 = weak)")